package store

import (
	"context"
	"database/sql"
	"errors"
	"time"
)

// ContentBrief is a Markdown action plan for a losing prompt, generated by
// `salience brief`. Stored so dashboards and follow-up runs can reference it.
type ContentBrief struct {
	ID           int64
	ProjectID    int64
	Prompt       string
	BodyMarkdown string
	SourceRunID  int64
	CreatedAt    time.Time
}

// InsertContentBrief persists a brief.
func (s *Store) InsertContentBrief(ctx context.Context, b ContentBrief) (int64, error) {
	var srcRunID any
	if b.SourceRunID > 0 {
		srcRunID = b.SourceRunID
	}
	res, err := s.db.ExecContext(ctx, `
		INSERT INTO content_briefs(project_id, prompt, body_markdown, source_run_id, created_at)
		VALUES(?,?,?,?,?)`,
		b.ProjectID, b.Prompt, b.BodyMarkdown, srcRunID,
		time.Now().UTC().Format(time.RFC3339Nano))
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

// ListContentBriefs returns briefs for a project, newest first.
func (s *Store) ListContentBriefs(ctx context.Context, projectID int64) ([]ContentBrief, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT id, project_id, prompt, body_markdown, COALESCE(source_run_id, 0), created_at
		FROM content_briefs WHERE project_id=? ORDER BY id DESC`, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ContentBrief
	for rows.Next() {
		var b ContentBrief
		var created string
		if err := rows.Scan(&b.ID, &b.ProjectID, &b.Prompt, &b.BodyMarkdown,
			&b.SourceRunID, &created); err != nil {
			return nil, err
		}
		if t, err := time.Parse(time.RFC3339Nano, created); err == nil {
			b.CreatedAt = t
		}
		out = append(out, b)
	}
	return out, rows.Err()
}

// GetContentBrief returns a brief by id.
func (s *Store) GetContentBrief(ctx context.Context, id int64) (*ContentBrief, error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT id, project_id, prompt, body_markdown, COALESCE(source_run_id, 0), created_at
		FROM content_briefs WHERE id=?`, id)
	var b ContentBrief
	var created string
	if err := row.Scan(&b.ID, &b.ProjectID, &b.Prompt, &b.BodyMarkdown,
		&b.SourceRunID, &created); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, errors.New("content brief not found")
		}
		return nil, err
	}
	if t, err := time.Parse(time.RFC3339Nano, created); err == nil {
		b.CreatedAt = t
	}
	return &b, nil
}
